package am.developer.client.exception;

public enum ErrorType {
    FILE_DOWNLOAD_ERROR,
    FILE_UPLOAD_ERROR,
    FILE_MODERATION_ERROR,
    FILE_DELETE_ERROR,
    FILE_LIST_RETRIEVE_ERROR,
    FILE_SEARCH_ERROR,
    CATEGORY_LIST_RETRIEVE_ERROR,
    USER_DELETE_ERROR,
    USER_EDIT_ERROR,
    USER_LIST_RETRIEVE_ERROR,
    USER_AUTHENTICATE_ERROR,
    USER_RETRIEVE_ERROR,
    ROLE_LIST_RETRIEVE_ERROR,
    ROLE_RETRIEVE_ERROR,
    VIDEO_REQUEST_LIST_RETRIEVE_ERROR,
    VIDEO_REQUEST_RETRIEVE_ERROR,
    VIDEO_NOT_DELETED_REQUEST_RETRIEVE_ERROR,
    VIDEO_NOT_CLOSED_REQUEST_RETRIEVE_ERROR,
    VIDEO_REQUEST_ADD_ERROR,
    VIDEO_REQUEST_REPLY_ERROR,
    VIDEO_REQUEST_EDIT_ERROR
}
